### ISSUE TITLE
Learn WordPress Content Error Report - Ticket 138269

### ISSUE THREAD

**Issue by meaganhanes** [WordPress/Learn#1106]
# Error Description
- Content URL: https://learn.wordpress.org/learn/lesson/a-walk-around-the-dashboard/

In the Getting Started With WordPress: Get Familiar tutorial, at the bottom of the Walk Around the Dashboard page under the title Optional: An In-Depth Look at the Dashboard - there is a link to "A Deeper Dive into Settings Workshop". The link is broken and directs to a page that displays the following message: "There is no quiz for this lesson - click the 'complete lesson' button below to continue through the course." instead of the tutorial on additional dashboard controls.

Proposed Fix: Find the correct asset's URL or remove the Optional: An In-Depth Look at the Dashboard section entirely.

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by webtechpooja** [comment]
@meaganhanes Thanks for reporting the issue. This has been fixed now. Could you please verify it?

**Comment by jomarieminney** [comment]
I've just tested and it is still happening for me - please see screen capture: https://www.screencast.com/t/8wh1ogCHo6Sj

**Comment by kaitohm** [comment]
I think I've fixed this once and for all! Could you check again, @jomarieminney , to make sure it works for you now?

**Comment by jomarieminney** [comment]
can confirm it now goes to [WordPress Dashboard Overview Tutorial](https://learn.wordpress.org/tutorial/wordpress-dashboard-overview/) and no longer goes to the nasty 'there is no quiz for this lesson' page. :)

**Comment by meaganhanes** [comment]
Fully confirmed. We can now close this ticket. Thanks for the help y'all!
